"""add phone number for flexible login

Revision ID: 0f9f665bbd64
Revises: 
Create Date: 2026-02-27 22:00:14.432734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f9f665bbd64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_hint', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('active', 'revoked', 'expired', name='sessionstatus'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('ix_user_sessions_user_status', 'user_sessions', ['user_id', 'status'], unique=False)
    op.alter_column('categories', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('ix_categories_user_type', 'categories', ['user_id', 'type'], unique=False)
    op.alter_column('debts', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('debts', 'status',
               existing_type=postgresql.ENUM('unpaid', 'partially_paid', 'paid', name='debt_status'),
               server_default=None,
               nullable=False)
    op.alter_column('debts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('debts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_debts_user_id', 'debts', ['user_id'], unique=False)
    op.create_index('ix_debts_user_status', 'debts', ['user_id', 'status'], unique=False)
    op.alter_column('financial_goals', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('financial_goals', 'current_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=None,
               nullable=False)
    op.alter_column('financial_goals', 'status',
               existing_type=postgresql.ENUM('in_progress', 'completed', 'cancelled', name='goal_status'),
               server_default=None,
               nullable=False)
    op.alter_column('financial_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('financial_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_financial_goals_user_id', 'financial_goals', ['user_id'], unique=False)
    op.create_index('ix_financial_goals_user_status', 'financial_goals', ['user_id', 'status'], unique=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('unread', 'read', name='notificationstatus'),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.alter_column('receivables', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('receivables', 'status',
               existing_type=postgresql.ENUM('unpaid', 'partially_paid', 'paid', name='debt_status'),
               server_default=None,
               nullable=False)
    op.alter_column('receivables', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('receivables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('ix_receivables_user_id', 'receivables', ['user_id'], unique=False)
    op.create_index('ix_receivables_user_status', 'receivables', ['user_id', 'status'], unique=False)
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_transactions_date'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_type'), table_name='transactions')
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_type', 'transactions', ['user_id', 'type'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='userrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'tier',
               existing_type=postgresql.ENUM('regular', 'premium', name='usertier'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.create_unique_constraint(None, 'users', ['phone_number'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'tier',
               existing_type=postgresql.ENUM('regular', 'premium', name='usertier'),
               server_default=sa.text("'regular'::usertier"),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', name='userrole'),
               server_default=sa.text("'user'::userrole"),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'email')
    op.drop_index('ix_transactions_user_type', table_name='transactions')
    op.drop_index('ix_transactions_user_id', table_name='transactions')
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.create_index(op.f('idx_transactions_type'), 'transactions', ['type'], unique=False)
    op.create_index(op.f('idx_transactions_date'), 'transactions', ['transaction_date'], unique=False)
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('transactions', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.drop_index('ix_receivables_user_status', table_name='receivables')
    op.drop_index('ix_receivables_user_id', table_name='receivables')
    op.alter_column('receivables', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('receivables', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('receivables', 'status',
               existing_type=postgresql.ENUM('unpaid', 'partially_paid', 'paid', name='debt_status'),
               server_default=sa.text("'unpaid'::debt_status"),
               nullable=True)
    op.alter_column('receivables', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notifications', 'status',
               existing_type=postgresql.ENUM('unread', 'read', name='notificationstatus'),
               nullable=True)
    op.alter_column('notifications', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('ix_financial_goals_user_status', table_name='financial_goals')
    op.drop_index('ix_financial_goals_user_id', table_name='financial_goals')
    op.alter_column('financial_goals', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('financial_goals', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('financial_goals', 'status',
               existing_type=postgresql.ENUM('in_progress', 'completed', 'cancelled', name='goal_status'),
               server_default=sa.text("'in_progress'::goal_status"),
               nullable=True)
    op.alter_column('financial_goals', 'current_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('financial_goals', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.drop_index('ix_debts_user_status', table_name='debts')
    op.drop_index('ix_debts_user_id', table_name='debts')
    op.alter_column('debts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('debts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('debts', 'status',
               existing_type=postgresql.ENUM('unpaid', 'partially_paid', 'paid', name='debt_status'),
               server_default=sa.text("'unpaid'::debt_status"),
               nullable=True)
    op.alter_column('debts', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.drop_index('ix_categories_user_type', table_name='categories')
    op.drop_index('ix_categories_user_id', table_name='categories')
    op.alter_column('categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('categories', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.drop_index('ix_user_sessions_user_status', table_name='user_sessions')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
